eureka:
  client:
    serviceUrl:
#      defaultZone: http://spring-eureka:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8763

mybatis:
  type-aliases-package: nnero.domain
  config-location: classpath:nnero/mybatis-config.xml
  mapper-locations: classpath:nnero/mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article?useUnicode=true&characterEncoding=UTF8
    username: root
    password: nnero


logging:
  level:
    root: INFO
  file: ./user.log