
server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    root: INFO
    nnero: INFO
  file: ./eureka.log

