eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9000

zuul:
  routes:
    api-user:
      path: /api/user/**
      serviceId: service-user
    api-article:
      path: /api/article/**
      serviceId: service-article
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1